### ISSUE TITLE
some bugs

### ISSUE THREAD

**Issue by q8-hma** [Yupy/BtiTracker-1.5.1#1]
Hello

i find some bugs

`Fatal error: Class 'ocr_captcha' not found in /home/xx/public_html/xx/recover.php on line 225
`

login
`        elseif (md5($row['random'].$row['password'].$row['random']) != md5($row['random'].md5($pwd).$row['random'])) {
`
in reset pass in recover
`    $db->query("UPDATE users SET password = '" . md5($newpassword) . "' WHERE id = " . $id . " AND random = " . $random);
`
in account
`    @$db->query("INSERT INTO users (username, password, random, id_level, email, style, language, flag, joined, lastconnect, pid, time_offset) VALUES ('" . $utente . "', '" . md5($pwd) . "', " . $random . ", " . $idlevel . ", '" . $email . "', " . $idstyle . ", " . $idlangue . ", " . $idflag . ", NOW(), NOW(), '" . md5(uniqid(mt_rand(), true)) . "', '" . $timezone . "')") or sqlerr(__FILE__, __LINE__);
`
not same md5 

this for now and i will read all the files soon

thnx for all this

**Comment by Yupy** [comment]
Ty for posting the issue, I will fix it right away... did modified the class to work with PHP7 forgot to edit the recover also

**Comment by q8-hma** [comment]
thnx i will test the new one now
