### ISSUE TITLE
Missing some files of smarty class

### ISSUE THREAD

**Issue by bernalau** [Yupy/BtiTracker-1.5.1#2]
hello. 

I have install your application and configure without issue. 
But when i tried to access homepage, i had error 500.

In log of my webserver, it said your app search two files : 
sysplugins/smarty_template_resource_base.php
sysplugins/smarty_internal_extension_handler.php

I downloaded the files from https://github.com/smarty-php/smarty
After issue resolved !!!

Regards.

**Comment by Yupy** [comment]
Ty for the heads up, I will add the missing files.
